export class Constants {
  public static readonly PAGE_ENTRY = "entry_page"
  public static readonly PAGE_ENTRY2 = "entry_page2"
  public static readonly TEST_PAGE2 = "test_page2"
  public static readonly TEST_SERVICE = "TestService"
  public static readonly TEST_SERVICE2 = "TestService2"
  public static readonly GLOBAL_INTERCEPTOR = "GlobalInterceptor"
  public static readonly SPECIAL_INTERCEPTOR = "SpecialInterceptor"
}